//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace AK.Wwise.InfoFile {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SoundBanksInfo {
        
        private SoundBanksInfoRootPaths rootPathsField;
        
        private SoundBanksInfoDialogueEvents dialogueEventsField;
        
        private SoundBanksInfoSoundBanks soundBanksField;
        
        private string fileHashField;
        
        private string platformField;
        
        private SoundBanksInfoBasePlatform basePlatformField;
        
        private uint schemaVersionField;
        
        private uint soundBankVersionField;
        
        /// <remarks/>
        public SoundBanksInfoRootPaths RootPaths {
            get {
                return this.rootPathsField;
            }
            set {
                this.rootPathsField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoDialogueEvents DialogueEvents {
            get {
                return this.dialogueEventsField;
            }
            set {
                this.dialogueEventsField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanks SoundBanks {
            get {
                return this.soundBanksField;
            }
            set {
                this.soundBanksField = value;
            }
        }
        
        /// <remarks/>
        public string FileHash {
            get {
                return this.fileHashField;
            }
            set {
                this.fileHashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SoundBanksInfoBasePlatform BasePlatform {
            get {
                return this.basePlatformField;
            }
            set {
                this.basePlatformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint SchemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint SoundBankVersion {
            get {
                return this.soundBankVersionField;
            }
            set {
                this.soundBankVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoRootPaths {
        
        private string projectRootField;
        
        private string sourceFilesRootField;
        
        private string soundBanksRootField;
        
        private string externalSourcesInputFileField;
        
        private string externalSourcesOutputRootField;
        
        /// <remarks/>
        public string ProjectRoot {
            get {
                return this.projectRootField;
            }
            set {
                this.projectRootField = value;
            }
        }
        
        /// <remarks/>
        public string SourceFilesRoot {
            get {
                return this.sourceFilesRootField;
            }
            set {
                this.sourceFilesRootField = value;
            }
        }
        
        /// <remarks/>
        public string SoundBanksRoot {
            get {
                return this.soundBanksRootField;
            }
            set {
                this.soundBanksRootField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalSourcesInputFile {
            get {
                return this.externalSourcesInputFileField;
            }
            set {
                this.externalSourcesInputFileField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalSourcesOutputRoot {
            get {
                return this.externalSourcesOutputRootField;
            }
            set {
                this.externalSourcesOutputRootField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SwitchValueType {
        
        private SwitchValueTypeGroupType groupTypeField;
        
        private uint groupIdField;
        
        private uint idField;
        
        private string gUIDField;
        
        private bool defaultField;
        
        public SwitchValueType() {
            this.defaultField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SwitchValueTypeGroupType GroupType {
            get {
                return this.groupTypeField;
            }
            set {
                this.groupTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum SwitchValueTypeGroupType {
        
        /// <remarks/>
        Switch,
        
        /// <remarks/>
        State,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SwitchContainerType {
        
        private SwitchValueType switchValueField;
        
        private MediaReferenceList mediaRefsField;
        
        private ExternalSourceReferenceList externalSourceRefsField;
        
        private PluginReferenceGroup pluginRefsField;
        
        private SwitchContainerTypeChildren childrenField;
        
        /// <remarks/>
        public SwitchValueType SwitchValue {
            get {
                return this.switchValueField;
            }
            set {
                this.switchValueField = value;
            }
        }
        
        /// <remarks/>
        public MediaReferenceList MediaRefs {
            get {
                return this.mediaRefsField;
            }
            set {
                this.mediaRefsField = value;
            }
        }
        
        /// <remarks/>
        public ExternalSourceReferenceList ExternalSourceRefs {
            get {
                return this.externalSourceRefsField;
            }
            set {
                this.externalSourceRefsField = value;
            }
        }
        
        /// <remarks/>
        public PluginReferenceGroup PluginRefs {
            get {
                return this.pluginRefsField;
            }
            set {
                this.pluginRefsField = value;
            }
        }
        
        /// <remarks/>
        public SwitchContainerTypeChildren Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MediaReferenceList {
        
        private MediaReferenceListMediaRef[] mediaRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MediaRef")]
        public MediaReferenceListMediaRef[] MediaRef {
            get {
                return this.mediaRefField;
            }
            set {
                this.mediaRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaReferenceListMediaRef : MediaReferenceType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MediaReferenceType {
        
        private uint idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExternalSourceReferenceList {
        
        private ExternalSourceReferenceListExternalSourceRef[] externalSourceRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalSourceRef")]
        public ExternalSourceReferenceListExternalSourceRef[] ExternalSourceRef {
            get {
                return this.externalSourceRefField;
            }
            set {
                this.externalSourceRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ExternalSourceReferenceListExternalSourceRef : ExternalSourceReferenceType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExternalSourceReferenceType {
        
        private uint cookieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Cookie {
            get {
                return this.cookieField;
            }
            set {
                this.cookieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PluginReferenceGroup {
        
        private PluginReferenceType[] customField;
        
        private PluginReferenceType[] sharesetsField;
        
        private PluginReferenceType[] audioDevicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PluginRef", IsNullable=false)]
        public PluginReferenceType[] Custom {
            get {
                return this.customField;
            }
            set {
                this.customField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PluginRef", IsNullable=false)]
        public PluginReferenceType[] Sharesets {
            get {
                return this.sharesetsField;
            }
            set {
                this.sharesetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PluginRef", IsNullable=false)]
        public PluginReferenceType[] AudioDevices {
            get {
                return this.audioDevicesField;
            }
            set {
                this.audioDevicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PluginReferenceType {
        
        private uint idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SwitchContainerTypeChildren {
        
        private SwitchContainerTypeChildrenSwitchContainer[] switchContainerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SwitchContainer")]
        public SwitchContainerTypeChildrenSwitchContainer[] SwitchContainer {
            get {
                return this.switchContainerField;
            }
            set {
                this.switchContainerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SwitchContainerTypeChildrenSwitchContainer : SwitchContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PluginGroup {
        
        private PluginType[] customField;
        
        private PluginType[] sharesetsField;
        
        private PluginType[] audioDevicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Plugin", IsNullable=false)]
        public PluginType[] Custom {
            get {
                return this.customField;
            }
            set {
                this.customField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Plugin", IsNullable=false)]
        public PluginType[] Sharesets {
            get {
                return this.sharesetsField;
            }
            set {
                this.sharesetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Plugin", IsNullable=false)]
        public PluginType[] AudioDevices {
            get {
                return this.audioDevicesField;
            }
            set {
                this.audioDevicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PluginType : NameID {
        
        private MediaReferenceList mediaRefsField;
        
        private PluginReferenceGroup pluginRefsField;
        
        private string libNameField;
        
        private uint libIdField;
        
        /// <remarks/>
        public MediaReferenceList MediaRefs {
            get {
                return this.mediaRefsField;
            }
            set {
                this.mediaRefsField = value;
            }
        }
        
        /// <remarks/>
        public PluginReferenceGroup PluginRefs {
            get {
                return this.pluginRefsField;
            }
            set {
                this.pluginRefsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LibName {
            get {
                return this.libNameField;
            }
            set {
                this.libNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint LibId {
            get {
                return this.libIdField;
            }
            set {
                this.libIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupNameID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DialogueEventType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuxBusReferenceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PluginType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NameID {
        
        private uint idField;
        
        private string nameField;
        
        private string objectPathField;
        
        private string gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectPath {
            get {
                return this.objectPathField;
            }
            set {
                this.objectPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupNameID : NameID {
        
        private uint groupIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DialogueEventType : NameID {
        
        private DialogueEventTypeArguments[] argumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Arguments")]
        public DialogueEventTypeArguments[] Arguments {
            get {
                return this.argumentsField;
            }
            set {
                this.argumentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DialogueEventTypeArguments {
        
        private NameID[] argumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Argument")]
        public NameID[] Argument {
            get {
                return this.argumentField;
            }
            set {
                this.argumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuxBusReferenceType : NameID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BusType : NameID {
        
        private PluginReferenceGroup pluginRefsField;
        
        private AuxBusReferenceList auxBusRefsField;
        
        /// <remarks/>
        public PluginReferenceGroup PluginRefs {
            get {
                return this.pluginRefsField;
            }
            set {
                this.pluginRefsField = value;
            }
        }
        
        /// <remarks/>
        public AuxBusReferenceList AuxBusRefs {
            get {
                return this.auxBusRefsField;
            }
            set {
                this.auxBusRefsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuxBusReferenceList {
        
        private AuxBusReferenceListAuxBusRef[] auxBusRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AuxBusRef")]
        public AuxBusReferenceListAuxBusRef[] AuxBusRef {
            get {
                return this.auxBusRefField;
            }
            set {
                this.auxBusRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class AuxBusReferenceListAuxBusRef : AuxBusReferenceType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NameCookie {
        
        private uint cookieField;
        
        private string nameField;
        
        private string objectPathField;
        
        private string gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Cookie {
            get {
                return this.cookieField;
            }
            set {
                this.cookieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectPath {
            get {
                return this.objectPathField;
            }
            set {
                this.objectPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MediaDescriptorList {
        
        private MediaDescriptorListFile[] fileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("File")]
        public MediaDescriptorListFile[] File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MediaDescriptorListFile : MediaDescriptorType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MediaDescriptorType : FileDescriptorType {
        
        private string cachePathField;
        
        private uint prefetchSizeField;
        
        private bool prefetchSizeFieldSpecified;
        
        private bool streamingField;
        
        private Location locationField;
        
        private bool usingReferenceLanguageField;
        
        public MediaDescriptorType() {
            this.streamingField = false;
            this.locationField = Location.Loose;
            this.usingReferenceLanguageField = false;
        }
        
        /// <remarks/>
        public string CachePath {
            get {
                return this.cachePathField;
            }
            set {
                this.cachePathField = value;
            }
        }
        
        /// <remarks/>
        public uint PrefetchSize {
            get {
                return this.prefetchSizeField;
            }
            set {
                this.prefetchSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrefetchSizeSpecified {
            get {
                return this.prefetchSizeFieldSpecified;
            }
            set {
                this.prefetchSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Streaming {
            get {
                return this.streamingField;
            }
            set {
                this.streamingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(Location.Loose)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UsingReferenceLanguage {
            get {
                return this.usingReferenceLanguageField;
            }
            set {
                this.usingReferenceLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum Location {
        
        /// <remarks/>
        Memory,
        
        /// <remarks/>
        Loose,
        
        /// <remarks/>
        OtherBank,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MediaDescriptorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BankDescriptorType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileDescriptorType {
        
        private string objectPathField;
        
        private string shortNameField;
        
        private string pathField;
        
        private uint idField;
        
        private string languageField;
        
        private uint alignField;
        
        private bool deviceMemoryField;
        
        public FileDescriptorType() {
            this.alignField = ((uint)(0));
            this.deviceMemoryField = false;
        }
        
        /// <remarks/>
        public string ObjectPath {
            get {
                return this.objectPathField;
            }
            set {
                this.objectPathField = value;
            }
        }
        
        /// <remarks/>
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint Align {
            get {
                return this.alignField;
            }
            set {
                this.alignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DeviceMemory {
            get {
                return this.deviceMemoryField;
            }
            set {
                this.deviceMemoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BankDescriptorType : FileDescriptorType {
        
        private string gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoDialogueEvents {
        
        private DialogueEventType[] dialogueEventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DialogueEvent")]
        public DialogueEventType[] DialogueEvent {
            get {
                return this.dialogueEventField;
            }
            set {
                this.dialogueEventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanks {
        
        private SoundBanksInfoSoundBanksSoundBank[] soundBankField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoundBank")]
        public SoundBanksInfoSoundBanksSoundBank[] SoundBank {
            get {
                return this.soundBankField;
            }
            set {
                this.soundBankField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBank : BankDescriptorType {
        
        private SoundBanksInfoSoundBanksSoundBankMedia mediaField;
        
        private SoundBanksInfoSoundBanksSoundBankExternalSources externalSourcesField;
        
        private PluginGroup pluginsField;
        
        private SoundBanksInfoSoundBanksSoundBankEvents eventsField;
        
        private SoundBanksInfoSoundBanksSoundBankDialogueEvents dialogueEventsField;
        
        private SoundBanksInfoSoundBanksSoundBankBusses bussesField;
        
        private SoundBanksInfoSoundBanksSoundBankAuxBusses auxBussesField;
        
        private SoundBanksInfoSoundBanksSoundBankGameParameters gameParametersField;
        
        private SoundBanksInfoSoundBanksSoundBankStateGroups stateGroupsField;
        
        private SoundBanksInfoSoundBanksSoundBankSwitchGroups switchGroupsField;
        
        private SoundBanksInfoSoundBanksSoundBankTriggers triggersField;
        
        private SoundBanksInfoSoundBanksSoundBankAcousticTextures acousticTexturesField;
        
        private string hashField;
        
        private string typeField;
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankMedia Media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankExternalSources ExternalSources {
            get {
                return this.externalSourcesField;
            }
            set {
                this.externalSourcesField = value;
            }
        }
        
        /// <remarks/>
        public PluginGroup Plugins {
            get {
                return this.pluginsField;
            }
            set {
                this.pluginsField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankEvents Events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankDialogueEvents DialogueEvents {
            get {
                return this.dialogueEventsField;
            }
            set {
                this.dialogueEventsField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankBusses Busses {
            get {
                return this.bussesField;
            }
            set {
                this.bussesField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankAuxBusses AuxBusses {
            get {
                return this.auxBussesField;
            }
            set {
                this.auxBussesField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankGameParameters GameParameters {
            get {
                return this.gameParametersField;
            }
            set {
                this.gameParametersField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankStateGroups StateGroups {
            get {
                return this.stateGroupsField;
            }
            set {
                this.stateGroupsField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankSwitchGroups SwitchGroups {
            get {
                return this.switchGroupsField;
            }
            set {
                this.switchGroupsField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankTriggers Triggers {
            get {
                return this.triggersField;
            }
            set {
                this.triggersField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankAcousticTextures AcousticTextures {
            get {
                return this.acousticTexturesField;
            }
            set {
                this.acousticTexturesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankMedia : MediaDescriptorList {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankExternalSources {
        
        private SoundBanksInfoSoundBanksSoundBankExternalSourcesSource[] sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Source")]
        public SoundBanksInfoSoundBanksSoundBankExternalSourcesSource[] Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankExternalSourcesSource : NameCookie {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEvents {
        
        private SoundBanksInfoSoundBanksSoundBankEventsEvent[] eventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Event")]
        public SoundBanksInfoSoundBanksSoundBankEventsEvent[] Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEvent : NameID {
        
        private MediaReferenceList mediaRefsField;
        
        private ExternalSourceReferenceList externalSourceRefsField;
        
        private PluginReferenceGroup pluginRefsField;
        
        private AuxBusReferenceList auxBusRefsField;
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventSwitchContainers switchContainersField;
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventActionPostEvent actionPostEventField;
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventActionSetState actionSetStateField;
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventActionSetSwitch actionSetSwitchField;
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventActionTrigger actionTriggerField;
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventActionSetFX actionSetFXField;
        
        private double maxAttenuationField;
        
        private bool maxAttenuationFieldSpecified;
        
        private string durationTypeField;
        
        private string durationMinField;
        
        private string durationMaxField;
        
        /// <remarks/>
        public MediaReferenceList MediaRefs {
            get {
                return this.mediaRefsField;
            }
            set {
                this.mediaRefsField = value;
            }
        }
        
        /// <remarks/>
        public ExternalSourceReferenceList ExternalSourceRefs {
            get {
                return this.externalSourceRefsField;
            }
            set {
                this.externalSourceRefsField = value;
            }
        }
        
        /// <remarks/>
        public PluginReferenceGroup PluginRefs {
            get {
                return this.pluginRefsField;
            }
            set {
                this.pluginRefsField = value;
            }
        }
        
        /// <remarks/>
        public AuxBusReferenceList AuxBusRefs {
            get {
                return this.auxBusRefsField;
            }
            set {
                this.auxBusRefsField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankEventsEventSwitchContainers SwitchContainers {
            get {
                return this.switchContainersField;
            }
            set {
                this.switchContainersField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankEventsEventActionPostEvent ActionPostEvent {
            get {
                return this.actionPostEventField;
            }
            set {
                this.actionPostEventField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankEventsEventActionSetState ActionSetState {
            get {
                return this.actionSetStateField;
            }
            set {
                this.actionSetStateField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankEventsEventActionSetSwitch ActionSetSwitch {
            get {
                return this.actionSetSwitchField;
            }
            set {
                this.actionSetSwitchField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankEventsEventActionTrigger ActionTrigger {
            get {
                return this.actionTriggerField;
            }
            set {
                this.actionTriggerField = value;
            }
        }
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankEventsEventActionSetFX ActionSetFX {
            get {
                return this.actionSetFXField;
            }
            set {
                this.actionSetFXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double MaxAttenuation {
            get {
                return this.maxAttenuationField;
            }
            set {
                this.maxAttenuationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxAttenuationSpecified {
            get {
                return this.maxAttenuationFieldSpecified;
            }
            set {
                this.maxAttenuationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DurationType {
            get {
                return this.durationTypeField;
            }
            set {
                this.durationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DurationMin {
            get {
                return this.durationMinField;
            }
            set {
                this.durationMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DurationMax {
            get {
                return this.durationMaxField;
            }
            set {
                this.durationMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventSwitchContainers {
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventSwitchContainersSwitchContainer[] switchContainerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SwitchContainer")]
        public SoundBanksInfoSoundBanksSoundBankEventsEventSwitchContainersSwitchContainer[] SwitchContainer {
            get {
                return this.switchContainerField;
            }
            set {
                this.switchContainerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventSwitchContainersSwitchContainer : SwitchContainerType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventActionPostEvent {
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventActionPostEventActionPostEventEntry[] actionPostEventEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionPostEventEntry")]
        public SoundBanksInfoSoundBanksSoundBankEventsEventActionPostEventActionPostEventEntry[] ActionPostEventEntry {
            get {
                return this.actionPostEventEntryField;
            }
            set {
                this.actionPostEventEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventActionPostEventActionPostEventEntry : NameID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventActionSetState {
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventActionSetStateActionSetStateEntry[] actionSetStateEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionSetStateEntry")]
        public SoundBanksInfoSoundBanksSoundBankEventsEventActionSetStateActionSetStateEntry[] ActionSetStateEntry {
            get {
                return this.actionSetStateEntryField;
            }
            set {
                this.actionSetStateEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventActionSetStateActionSetStateEntry : GroupNameID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventActionSetSwitch {
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventActionSetSwitchActionSetSwitchEntry[] actionSetSwitchEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionSetSwitchEntry")]
        public SoundBanksInfoSoundBanksSoundBankEventsEventActionSetSwitchActionSetSwitchEntry[] ActionSetSwitchEntry {
            get {
                return this.actionSetSwitchEntryField;
            }
            set {
                this.actionSetSwitchEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventActionSetSwitchActionSetSwitchEntry : GroupNameID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventActionTrigger {
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventActionTriggerActionTriggerEntry[] actionTriggerEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionTriggerEntry")]
        public SoundBanksInfoSoundBanksSoundBankEventsEventActionTriggerActionTriggerEntry[] ActionTriggerEntry {
            get {
                return this.actionTriggerEntryField;
            }
            set {
                this.actionTriggerEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventActionTriggerActionTriggerEntry : NameID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventActionSetFX {
        
        private SoundBanksInfoSoundBanksSoundBankEventsEventActionSetFXActionSetFXEntry[] actionSetFXEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActionSetFXEntry")]
        public SoundBanksInfoSoundBanksSoundBankEventsEventActionSetFXActionSetFXEntry[] ActionSetFXEntry {
            get {
                return this.actionSetFXEntryField;
            }
            set {
                this.actionSetFXEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankEventsEventActionSetFXActionSetFXEntry : NameID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankDialogueEvents {
        
        private DialogueEventType[] dialogueEventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DialogueEvent")]
        public DialogueEventType[] DialogueEvent {
            get {
                return this.dialogueEventField;
            }
            set {
                this.dialogueEventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankBusses {
        
        private SoundBanksInfoSoundBanksSoundBankBussesBus[] busField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bus")]
        public SoundBanksInfoSoundBanksSoundBankBussesBus[] Bus {
            get {
                return this.busField;
            }
            set {
                this.busField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankBussesBus : BusType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankAuxBusses {
        
        private SoundBanksInfoSoundBanksSoundBankAuxBussesAuxBus[] auxBusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AuxBus")]
        public SoundBanksInfoSoundBanksSoundBankAuxBussesAuxBus[] AuxBus {
            get {
                return this.auxBusField;
            }
            set {
                this.auxBusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankAuxBussesAuxBus : BusType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankGameParameters {
        
        private SoundBanksInfoSoundBanksSoundBankGameParametersGameParameter[] gameParameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GameParameter")]
        public SoundBanksInfoSoundBanksSoundBankGameParametersGameParameter[] GameParameter {
            get {
                return this.gameParameterField;
            }
            set {
                this.gameParameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankGameParametersGameParameter : NameID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankStateGroups {
        
        private SoundBanksInfoSoundBanksSoundBankStateGroupsStateGroup[] stateGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StateGroup")]
        public SoundBanksInfoSoundBanksSoundBankStateGroupsStateGroup[] StateGroup {
            get {
                return this.stateGroupField;
            }
            set {
                this.stateGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankStateGroupsStateGroup : NameID {
        
        private SoundBanksInfoSoundBanksSoundBankStateGroupsStateGroupStates[] statesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("States")]
        public SoundBanksInfoSoundBanksSoundBankStateGroupsStateGroupStates[] States {
            get {
                return this.statesField;
            }
            set {
                this.statesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankStateGroupsStateGroupStates {
        
        private SoundBanksInfoSoundBanksSoundBankStateGroupsStateGroupStatesState[] stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("State")]
        public SoundBanksInfoSoundBanksSoundBankStateGroupsStateGroupStatesState[] State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankStateGroupsStateGroupStatesState : NameID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankSwitchGroups {
        
        private SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroup[] switchGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SwitchGroup")]
        public SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroup[] SwitchGroup {
            get {
                return this.switchGroupField;
            }
            set {
                this.switchGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroup : NameID {
        
        private SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroupGameParameterRef[] gameParameterRefField;
        
        private SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroupSwitches[] switchesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GameParameterRef")]
        public SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroupGameParameterRef[] GameParameterRef {
            get {
                return this.gameParameterRefField;
            }
            set {
                this.gameParameterRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Switches")]
        public SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroupSwitches[] Switches {
            get {
                return this.switchesField;
            }
            set {
                this.switchesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroupGameParameterRef {
        
        private uint idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroupSwitches {
        
        private SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroupSwitchesSwitch[] switchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Switch")]
        public SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroupSwitchesSwitch[] Switch {
            get {
                return this.switchField;
            }
            set {
                this.switchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankSwitchGroupsSwitchGroupSwitchesSwitch : NameID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankTriggers {
        
        private SoundBanksInfoSoundBanksSoundBankTriggersTrigger[] triggerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Trigger")]
        public SoundBanksInfoSoundBanksSoundBankTriggersTrigger[] Trigger {
            get {
                return this.triggerField;
            }
            set {
                this.triggerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankTriggersTrigger : NameID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankAcousticTextures {
        
        private SoundBanksInfoSoundBanksSoundBankAcousticTexturesAcousticTexture[] acousticTextureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AcousticTexture")]
        public SoundBanksInfoSoundBanksSoundBankAcousticTexturesAcousticTexture[] AcousticTexture {
            get {
                return this.acousticTextureField;
            }
            set {
                this.acousticTextureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankAcousticTexturesAcousticTexture : NameID {
        
        private SoundBanksInfoSoundBanksSoundBankAcousticTexturesAcousticTextureProperties propertiesField;
        
        /// <remarks/>
        public SoundBanksInfoSoundBanksSoundBankAcousticTexturesAcousticTextureProperties Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankAcousticTexturesAcousticTextureProperties {
        
        private SoundBanksInfoSoundBanksSoundBankAcousticTexturesAcousticTexturePropertiesProperty[] propertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public SoundBanksInfoSoundBanksSoundBankAcousticTexturesAcousticTexturePropertiesProperty[] Property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SoundBanksInfoSoundBanksSoundBankAcousticTexturesAcousticTexturePropertiesProperty {
        
        private string nameField;
        
        private string typeField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum SoundBanksInfoBasePlatform {
        
        /// <remarks/>
        PS3,
        
        /// <remarks/>
        Wii,
        
        /// <remarks/>
        Windows,
        
        /// <remarks/>
        Xbox360,
        
        /// <remarks/>
        Mac,
        
        /// <remarks/>
        VitaSW,
        
        /// <remarks/>
        VitaHW,
        
        /// <remarks/>
        PS4,
        
        /// <remarks/>
        iOS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3DS")]
        Item3DS,
        
        /// <remarks/>
        WiiUSW,
        
        /// <remarks/>
        WiiUHW,
        
        /// <remarks/>
        Android,
        
        /// <remarks/>
        XboxOne,
        
        /// <remarks/>
        Linux,

        /// <remarks/>
        Stadia,

        /// <remarks/>
        WindowsPhone,
        
        /// <remarks/>
        Switch,
        
        /// <remarks/>
        Lumin,
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        PS5,
        
        /// <remarks/>
        XboxSeriesX,
    }
}
